name: Internal smCore Admin Module
description: |
    ...
identifier: org.smcore.admin
version: 1.0 Alpha 1
author:
    name: smCore Dev Team
    website: http://smcore.org

namespaces:
    php:      smCore\Modules\Admin
    lang:     admin
    template: admin

routes:
    main:
        match: [admin, admin/main]
        controller: Main
        method: main
    authenticate:
        match: admin/authenticate
        controller: Main
        method: authenticate
    end:
        match: admin/end
        controller: Main
        method: endSession

    configuration:
        match: admin/config
        controller: Configuration
        method: main

    modules:
        match: admin/modules
        controller: Modules
        method: main

    maintenance:
        match: admin/maintenance
        controller: Maintenance
        method: main
    maintenance_db:
        match: admin/maintenance/database
        controller: Maintenance
        method: database
    maintenance_cache:
        match: admin/maintenance/cache
        controller: Maintenance
        method: cache