name: smWiki Module
description: |
    This is the description for the smWiki module.
identifier: org.smwiki
version: 1.0
author:
    name: smWiki Dev Team
    website: http://simplewiki.co.uk

namespaces:
    php:      smCore\smWiki
    lang:     smWiki
    template: smWiki

routes:
    main:
        match: "wiki"
        controller: Main
        method: wikiMainMethod
    modify:
        match: "wiki/modify/(.*)"
        controller: Modify
        method: modifyMethod
    remove:
        match: "wiki/remove/(.*)"
        controller: Remove
        method: removeMethod
    protect:
        match: "wiki/protect/(.*)"
        controller: Protect
        method: protectMethod
    move:
        match: "wiki/move/(.*)"
        controller: Move
        method: moveMethod
    create:
        match: "wiki/create/(.*)"
        controller: Create
        method: createMethod
    create_blank:
        match: "wiki/create"
        controller: Create
        method: createMethod
    history:
        match: "wiki/history/(.*)"
        controller: History
        method: historyMethod
    revision:
        match: "wiki/revision/(.*)"
        controller: Revision
        method: revisionMethod
    view:
        match: "wiki/(.*)"
        controller: Main
        method: wikiPageMethod